# Generated by Django 4.1.7 on 2023-02-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Страна')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('street', models.CharField(max_length=50, verbose_name='Улица')),
                ('house_number', models.IntegerField(verbose_name='Номер дома')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Конакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contact')),
                ('name', models.CharField(max_length=100, verbose_name='Название завода')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('products', models.ManyToManyField(to='core.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Завод',
                'verbose_name_plural': 'Заводы',
            },
            bases=('core.contact',),
        ),
        migrations.CreateModel(
            name='Stores',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contact')),
                ('name', models.CharField(max_length=100, verbose_name='Название сети')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('products', models.ManyToManyField(to='core.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Розничная сеть',
                'verbose_name_plural': 'Розничные сети',
            },
            bases=('core.contact',),
        ),
        migrations.CreateModel(
            name='IndividualEntrepreneur',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contact')),
                ('name', models.CharField(max_length=100, verbose_name='Имя индивидуального предпринимателя')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('debt', models.FloatField(verbose_name='Задолженность перед поставщиком')),
                ('products', models.ManyToManyField(to='core.product', verbose_name='Продукты')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factory', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Индивидуальный предприниматель',
                'verbose_name_plural': 'Индивидуальные предприниматели',
            },
            bases=('core.contact',),
        ),
    ]
